### ISSUE TITLE
aeon API error - `Index out of bound error` raised in using `pelletdata`

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#10]
Code snippet to reproduce the error:

```
import pandas as pd
from aeon.preprocess import api as aeon_api


root = '/ceph/aeon/test2/experiment0.1'

time_bin_start = '2021-06-10 14:00:00'
time_bin_end = '2021-06-10 15:00:00'

pelletdata = aeon_api.pelletdata(root,
                                 device='Patch1',
                                 start=pd.Timestamp(time_bin_start),
                                 end=pd.Timestamp(time_bin_end))
```

The error stack:
```
Traceback (most recent call last):
  File "/nfs/nhome/live/thinh/.conda/envs/tn-aeon/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-e6aa4711fc3e>", line 1, in <module>
    pelletdata = aeon_api.pelletdata(raw_data_dir.as_posix(),
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/preprocess/api.py", line 326, in pelletdata
    beambreak = harpdata(path, device, register=32, names=['bitmask'], start=start, end=end)
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/preprocess/api.py", line 287, in harpdata
    return load(
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/preprocess/api.py", line 100, in load
    data = pd.concat([reader(file) for file in files])
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/preprocess/api.py", line 100, in <listcomp>
    data = pd.concat([reader(file) for file in files])
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/preprocess/api.py", line 289, in <lambda>
    lambda file: harpreader(file, names),
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/preprocess/api.py", line 256, in harpreader
    stride = data[1] + 2
IndexError: index 1 is out of bounds for axis 0 with size 0
```

**Comment by jkbhagatio** [comment]
Fixed, closing
