### ISSUE TITLE
corrupted log file

### ISSUE THREAD

**Issue by JaerongA** [SainsburyWellcomeCentre/aeon_mecha#153]
A log file named

'/ceph/aeon/aeon/data/raw/AEON2/experiment0.2/2022-02-23T17-26-31/ExperimentalMetadata/ExperimentalMetadata_MessageLog_2022-02-23T18-00-00.csv'

seems corrupted and yields the following error with `aeon.io.reader.CSV.read`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/nhome/live/jaeronga/.conda/envs/aeon/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/nfs/nhome/live/jaeronga/.conda/envs/aeon/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/nfs/nhome/live/jaeronga/.conda/envs/aeon/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/nfs/nhome/live/jaeronga/.conda/envs/aeon/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1255, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/nfs/nhome/live/jaeronga/.conda/envs/aeon/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 271, in read
    values = data.pop(self.index_col[i])
IndexError: list index out of range
```

Some log data couldn't be ingested properly into `ExperimentLog.Message` table as a result.

**Comment by ttngu207** [comment]
Another type of error, also from reading the log file
```
            log_messages = io_api.load(
                root='/ceph/aeon/aeon/data/raw/AEON2/experiment0.2',
                reader=device.MessageLog,
                start='2022-03-17 15:00:00',
                end='2022-03-17 16:00:00',
            )
````            

```
Traceback (most recent call last):
  File "/nfs/nhome/live/thinh/.conda/envs/aeon_env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-59-0026268428ce>", line 1, in <module>
    log_messages = io_api.load(
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/io/api.py", line 129, in load
    _set_index(data)
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/io/api.py", line 50, in _set_index
    data.index = aeon(data.index)
  File "/nfs/nhome/live/thinh/code/ProjectAeon/aeon/aeon/io/api.py", line 11, in aeon
    return datetime.datetime(1904, 1, 1) + pd.to_timedelta(seconds, 's')
  File "/nfs/nhome/live/thinh/.conda/envs/aeon_env/lib/python3.9/site-packages/pandas/core/tools/timedeltas.py", line 133, in to_timedelta
    return _convert_listlike(arg, unit=unit, errors=errors, name=arg.name)
  File "/nfs/nhome/live/thinh/.conda/envs/aeon_env/lib/python3.9/site-packages/pandas/core/tools/timedeltas.py", line 179, in _convert_listlike
    td64arr = sequence_to_td64ns(arg, unit=unit, errors=errors, copy=False)[0]
  File "/nfs/nhome/live/thinh/.conda/envs/aeon_env/lib/python3.9/site-packages/pandas/core/arrays/timedeltas.py", line 1001, in sequence_to_td64ns
    data = objects_to_td64ns(data, unit=unit, errors=errors)
  File "/nfs/nhome/live/thinh/.conda/envs/aeon_env/lib/python3.9/site-packages/pandas/core/arrays/timedeltas.py", line 1110, in objects_to_td64ns
    result = array_to_timedelta64(values, unit=unit, errors=errors)
  File "pandas/_libs/tslibs/timedeltas.pyx", line 340, in pandas._libs.tslibs.timedeltas.array_to_timedelta64
ValueError: unit must not be specified if the input contains a str
```

**Comment by ttngu207** [comment]
@jkbhagatio , @lochhh , to address this problem, @JaerongA has issued a PR #173 

However, the fix is basically to skip over any corrupted files and insert 0 entries for logs. This would allow us to move forward but again if there are truly log events during the `chunk` time period, those events will not get ingested due to the corrupted log files.

Let us know if you're OK with the DataJoint ingestion routine to move forward with this fix, or should we hold off and wait for a solution to fix the corrupted files?

**Comment by lochhh** [comment]
Thank you @ttngu207, @JaerongA . I guess we can move forward for now and later re-ingest when the fix for corrupted files is ready. Thoughts, @jkbhagatio?

**Comment by jkbhagatio** [comment]
There was a fix on the acquisition side to ensure this corruption doesn't occur again.
